
# \u914D\u7F6E\u6570\u636E\u5E93\u76F8\u5173\u4FE1\u606F
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tecs?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

# \u5F00\u542F\u65E5\u5FD7
logging:
  level:
    com.example.mapper: debug

#\u914D\u7F6E pagehelper \u63D2\u4EF6
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql